spring:
  application:
    name: eureka-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761
