
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761
