version: '3.8' # or '2.4'      # add
services: # add
  #  zipkin:
  #    image: openzipkin/zipkin
  #    container_name: zipkin
  #    ports:
  #      - "9411:9411"
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"